steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - us-central1-docker.pkg.dev/ordering-intelligence/services/order-service:latest
      - -f
      - backend/services/order-service/Dockerfile
      - .
images:
  - us-central1-docker.pkg.dev/ordering-intelligence/services/order-service:latest
