name: consumer_core
description: "Shared consumer models and APIs for Ordering Intelligence."
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ">=3.10.4 <4.0.0"

dependencies:
  http: ^1.2.1

