steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/services/agent-webhooks:latest"
      - "-f"
      - "backend/services/agent-webhooks/Dockerfile"
      - "."
images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/services/agent-webhooks:latest"


