steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_AR_HOST}/$PROJECT_ID/services/dispatch-service:${_TAG}"
      - "-f"
      - "backend/services/dispatch-service/Dockerfile"
      - "."
images:
  - "${_AR_HOST}/$PROJECT_ID/services/dispatch-service:${_TAG}"

substitutions:
  _AR_HOST: "europe-west1-docker.pkg.dev"
  _TAG: "latest"
