steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/services/customer-profile-service:latest"
      - "-f"
      - "backend/services/customer-profile-service/Dockerfile"
      - "."
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/services/customer-profile-service:latest"

substitutions:
  _REGION: europe-west1

